name: Coupon Collection

on:
  schedule:
    - cron: '0 10 * * 3'  # 每周三上午10点（北京时间）
  workflow_dispatch:

jobs:
  collect:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: |
          pip install selenium requests python-dotenv

      - name: Set up Chrome
        uses: google-github-actions/setup-chrome@v4
        with:
          chrome-version: 'stable'

      - name: Set up ChromeDriver
        uses: actions/setup-chromedriver@v3
        with:
          chrome-version: 'stable'

      - name: Run Coupon Bot
        env:
          NS_USER: ${{ secrets.NS_USER }}
          NS_PWD: ${{ secrets.NS_PWD }}
          PUSHPLUS_TOKEN: ${{ secrets.PUSHPLUS_TOKEN }}
        run: |
          python main.py
